### ISSUE TITLE
Индексный файл должен генерироваться автоматически

### ISSUE THREAD

**Issue by ulysses4ever** [mmcs-sfedu/PL_Lections_2014-2015#11]
Собственно, сабж. Что мы, не на ФИИТ что ли!

**Comment by ghost** [comment]
В markdown для этих целей предусмотрена какая-то функциональность? Или Вы предлагаете bash скрипт написать, который будет обновлять index.md?

**Comment by ulysses4ever** [comment]
К сожалению, ничего нет. Баш как вариант, да. Недостаток баша в том, что он непереносим. Я бы такое на Питоне писал, но ближайшие пару дней времени не будет, наверное.

Учтите, это идея. Я не считаю, что нужно прямо сейчас бросаться её делать. Но было бы хорошо вообще сделать.

**Comment by xamgore** [comment]
Java никто не любит :disappointed: 
Я все равно не помню python.

**Comment by ulysses4ever** [comment]
Джава хороший язык, но не очень подходит для обработки текста. Хотя мне всё равно.

**Comment by ulysses4ever** [comment]
На баше, вроде, тут решение есть: https://github.com/ekalinin/github-markdown-toc

**Comment by ghost** [comment]
Если что, сильно не ругайте - я питона сегодня первый раз за хвост тянул.

https://github.com/razykov/PL_Lections_2014-2015/blob/add-index_-gen/index_regen.py

**Comment by xamgore** [comment]
А я думал нужно что-то вроде зайти на github, забрать файлы, подготовить index, залить на github в виде коммита. Я ведь работаю только через веб-интерфейс.

**Comment by ulysses4ever** [comment]
Нет, только генерация.

**Comment by ulysses4ever** [comment]
Ссылка Массивы (лекция 4) неправильная.

**Comment by ghost** [comment]
Да, это из-за пробела после заголовка. Такая же проблема с ссылками содержащими "++", но только здесь дело в github'е. Сегодня днем займусь скриптом с якорями и эти проблемы решатся.

**Comment by ghost** [comment]
Теперь все ссылки рабочие, даже те, что содержат "++"
