### ISSUE TITLE
Программа экзамена

### ISSUE THREAD

**Issue by xamgore** [mmcs-sfedu/PL_Lections_2014-2015#2]
Предлагаю создать рядом файл "exam.md" / "exprogram.md" следующего содержания: http://dumpz.org/1206331/ . И постепенно добавлять ссылки и туда.

Конспекты сами по себе никому не нужны, а вот при подготовке к экзамену будет очень даже хорошо. Пробежался по списку тем глазами, кликнул на что-нибудь, что подзабыл и почитал.

**Comment by ulysses4ever** [comment]
Это отличная идея.

**Comment by ghost** [comment]
Xamgore, ты уже начал над этим работать или мне этим заняться? Это наша прошлогодняя программа экзамена или черновой вариант стоит попросить у Admin'a?

**Comment by ulysses4ever** [comment]
Вообще-то, сейчас и Ридми уже очень подробный и полезный; а программу, думаю, до января никто особо использовать не будет. Но решение за вами, конечно.

**Comment by ghost** [comment]
Мое мнение таково: идея очень стоящая и сделать такую программу надо, однако я бы отложил решение этого вопроса до конца ноября - начала декабря, когда будет почти законченный конспект лекций и когда можно будет говорить об окончательной программе экзамена.

**Comment by xamgore** [comment]
Вы тут сделали красивые странички (можно даже их Admin'у показать), только в конце каждой страницы ещё неплохо было бы прикрепить тройку ссылок (лекция n–1, содержание, лекция n+1). Чтобы уже как книгу смотреть. м?

**Comment by ghost** [comment]
Я бы еще предложил такую штуку вверху страницы сделать. Кстати содержание всего курса вверху страниц уже есть, или ты предлагаешь сделать еще небольшое содержание для каждой лекции?

**Comment by xamgore** [comment]
[to prev_lec] [to main page] [to next_lec]

**Comment by ulysses4ever** [comment]
Насчёт пажинации (ссылки на prev/next): да, это разумно, но силы тратить жаль. Проблема в том, что этот движок гитхабовский очень ограничен: многие вещи, которые легко запрограммировать, там запрещены. Мне без вперёд/назад нормально.

**Comment by xamgore** [comment]
В общем, надо начинать потихоньку работать над этой темой, экзамен через два месяца.
Преимущественно краткий набор утверждений, чтобы освежить память при подготовке.
Честно говоря, даже понятия не имею, как должен проходить экзамен.

**Comment by ulysses4ever** [comment]
В [УКД](http://edu.mmcs.sfedu.ru/pluginfile.php/9107/mod_resource/content/3/UKD-PLs.pdf) есть про экзамен. Программу, по-моему, рано. В принципе, не понимаю, чем может отличаться программа от списка тем на главной странице сайта. Может, если будет, минимально, это будет ясно только когда её выдадут, а это будет в конце декабря в лучшем случае.

**Comment by xamgore** [comment]
Целый модуль прошёл, можно уже начинать.
Моя цель: небольшие ответы, может, в виде некоторого плана. То есть кратко и по делу.
Лекции они всё-таки для того, чтобы разобраться, понять. Много-много слов. А для экзамена это не нужно.

[Прогресс](https://github.com/razykov/PL_Lections_2014-2015/blob/exam/exam/module1.md).

**Comment by xamgore** [comment]
На своём личном опыте убедился, что никакая программа экзамена не нужна и достаточно прочитать конспект, чтобы сдать экзамен на максимум.
