### ISSUE TITLE
Убрать der/ из url

### ISSUE THREAD

**Issue by ghost** [mmcs-sfedu/PL_Lections_2014-2015#21]
Папочка der/ по-прежнему отображается в url. Хотелось бы избавиться от этого без размещения сгенерированных файлов в корневом каталоге.

**Comment by ghost** [comment]
Я ночью экспериментировал с `__config.yml` ничего толкового не вышло, пришлось сделать большой откат. Сделать `der/` корневым каталогом  у меня получилось, но избавиться от `der/` в url так и не удалось

**Comment by ulysses4ever** [comment]
Я предлагаю сгенерированные файлы держать в корневом каталоге.

**Comment by ghost** [comment]
Ну, не знаю - неудобно это как-то.
Меня сейчас вот какая идея поселила:
Переименовать папку der/ в lectures/, а сгенерированные файлы с лекциями называть просто числами.

**Comment by ulysses4ever** [comment]
Почему неудобно, не понимаю. Вы очень сильно усложили проект уже. В то
время как основная задача программиста это борьба со сложностью.

Вариант с каталогом lectures , в принципе, симпатичный.

**Comment by ulysses4ever** [comment]
Кстати, вначале сгенерированных файлов обычно пишут комментарий типа: этот файл был сгенерирован автоматически, любые изменения будут утеряны при перегенерации. Большими буквами!

**Comment by ghost** [comment]
Хорошо. Учтем!

**Comment by ghost** [comment]
А в markdown существуют комментарии?
Я попытался вставить предупреждающее сообщение в начало автоматически генерируемых файлов в виде html-тега, но Pages отказываются генерировать из них страницы. Выдает 404.

**Comment by ulysses4ever** [comment]
Мы делаем комментарии в MD так:

```
[//]: <> ( текст комментария )
```

Комментарий HTML не должен ломать Pages, если его ставить после front matter (пара --- вначале), мне кажется. Но комментарий в HTML хуже, потому что он пойдёт к клиенту, а клиенту эта информация ни к чему.

**Comment by ghost** [comment]
В редакторе этого не видно, но в Pages это остается.

**Comment by ulysses4ever** [comment]
Не понял, прямо на github.io видно?

**Comment by ghost** [comment]
Да.

**Comment by ghost** [comment]
Сейчас поставил html комментарии их не видно.

**Comment by ghost** [comment]
Могу откатить, если хотите посмотреть, как отображаются `[//]: <> ( текст комментария )`

**Comment by ulysses4ever** [comment]
Да не надо, я верю.

**Comment by ulysses4ever** [comment]
Пусть будет HTML.
