### ISSUE TITLE
Ветвление

### ISSUE THREAD

**Issue by xamgore** [mmcs-sfedu/PL_Lections_2014-2015#22]
Когда у нас появилась папочка src, и отдельно генерируемый индекс, я вообще не понимаю, зачем нам все эти дополнительные ветки типа add-lecture-09. Почему бы тогда сразу в pages не редактировать? 

И второй вопрос, это чойта я теперь не смогу редактировать восьмую лекцию, только потому что такой ветки нет?

**Comment by ulysses4ever** [comment]
Использование веток это вопрос соглашений в проекте, он никак не связан с конкретной структурой каталогов. Считается, что новые задачи (например, добавление новой лекции) лучше делать в отдельных ветках, пока они не дошли до состояния релиза (в нашем случае: исправлены опечатки, добавлены рисунки и тому подобное). В принципе можно обходиться и без веток, тогда на сайте будут отображаться «недоделанные» лекции.

Вы спокойно можете редактировать старые лекции, которые уже попали в релиз (то есть в ветку gh-pages) без создания новых веток. Хотя есть проекты, где есть отдельная ветка для багфиксов. Но это всё имеет бОльший смысл для очень больших проектов.

**Comment by xamgore** [comment]
Так а почему недоделанные лекции должны будут отображаться на сайте?

Заливаем конспект новой лекции, доводим до нужного состояния, генерируем в индекс, всё. И все это в одной ветке.

**Comment by ulysses4ever** [comment]
Ну, организация работы такая. Это всё равно что спросить: зачем мне ходить
программировать на работу в офис, когда я и из дома прекрасно могу
программировать. Но так принято...

**Comment by ghost** [comment]
Я бы выделил два преимущества. 
Во-первых, на графе проекта сразу виден логический кусок - это упрощает навигацию по истории. Иначе будет одна длинная "кишка", и попробуй разбери, что к чему.
Во-вторых, в отдельной ветке, можно действовать абсолютно смело, не боясь сломать Pages и не проверять их работоспособность после каждого `push`. К тому же никто не застрахован, от того, что при добавлении новой лекции придется внести изменения в скрипт и следовательно проверить результат генерации. Поэтому вариант, когда `./build` мы делаем только в конце, не всегда реален.

**Comment by ulysses4ever** [comment]
@razykov а можете, кстати, ссылку дать, где это видно?

**Comment by xamgore** [comment]
> Виден логический кусок, иначе длинная "кишка", и попробуй разбери.

Коммиты надо нормально оформлять и всё будет ясно :wink:
https://wiki.openstack.org/wiki/GitCommitMessages

**Comment by xamgore** [comment]
> При добавлении новой лецкии может понадобиться внести изменения в скрипт.

Что за изменения? По каким причинам такое может произойти?

**Comment by ulysses4ever** [comment]
@Xamqore это всё равно что сказать: учите хорошо матанализ, тогда и алгебра не нужна. Или наоборот. Это «ложная дилемма», в нормальных проектах и коммиты хорошие, и ветки для структуризации работы используются.

**Comment by ulysses4ever** [comment]
> Что за изменения?

Да уже же много раз менялось, вы не в курсе? Не слышали, что при использовании ПО вскрываются недостатки, недоработки и т. п. Например, когда ++ в заголовках не парсился.

Так что абсолютно справедливо сказано.

**Comment by xamgore** [comment]
> Да уже же много раз менялось, вы не в курсе? 

Нет :smile:. Вернее, что-то видел, что-то нет. Но сорцы не глядел ни разу.

> ложная дилемма

Я, в общем, не предлагаю отмену ветвления как решение всех проблем. Просто говорю, что для обычного написания лекций как-то странно использовать эти самые ветки. Если проблема появляется на этапе перегенерации pages, то почему бы не ответвляться перед этой самой генерацией — если появятся проблемы в скрипте, или в отображениях pages, то пусть они и решаются в этой новой ветке. А /src то здесь причём?

Да и вообще, я просто люблю много поболтать. Ну и мне немножко лень делать плюс один клик (переход в другую ветку), вот.

**Comment by ulysses4ever** [comment]
В основную ветку не должно попадать то, что недоделано, то, что что-то ломает и т. п. Чтобы иметь гарантию этого, всё новое добавляется вначале в новую ветку.

**Comment by ghost** [comment]
`@razykov а можете, кстати, ссылку дать, где это видно?`

https://github.com/razykov/PL_Lections_2014-2015/network[1] 

ну или выполнить
`git log --graph`

Мне кажется так удобнее, когда коммиты, связанные одной 
задачей, визуально выделяются в истории проекта.

---

[1] https://github.com/razykov/PL_Lections_2014-2015/network

**Comment by xamgore** [comment]
> не должно попадать то, что недоделано, то, что что-то ломает 

Так речь как раз о том, что ничего туда плохого и не попадёт. Сорцы сами по себе никого и ничего не ломают. А вот перед этапом генерации (и последующей правки скрипта) — пожалуйста, делайте ветки сколько хотите. Главное, чтобы сорцы никто не трогал.
