### ISSUE TITLE
Кириллица в блоке кода, CSS

### ISSUE THREAD

**Issue by xamgore** [mmcs-sfedu/PL_Lections_2014-2015#29]
Посмотрите на содержимое первой лекции, в частности раздел "Условный оператор". Там в коде по каким-то причинам выделяется сильным красным цветом троеточие или русские слова.

В частности, виноват класс err: <span class="err">условие</span>

Надо его как-то подретушировать что ли.

**Comment by ghost** [comment]
Надо в файле syntax.css смотреть
