### ISSUE TITLE
Скрипт build.py валится

### ISSUE THREAD

**Issue by ulysses4ever** [mmcs-sfedu/PL_Lections_2014-2015#31]
Сообщение:

```
$ ./build.py 
Traceback (most recent call last):
  File "./build.py", line 14, in <module>
    make_der_files(args.refresh)
  File "/home/ulysses/Edu/Teaching/IT211/lectures/lectures-repo-razyv/scripts/project_rebuild.py", line 68, in make_der_files
    lect_file = open(lect_file_name, 'r', encoding='utf8')
TypeError: 'encoding' is an invalid keyword argument for this function
```

Я внёс правки по лекции 12, перегенерируйте файлы, пожалуйста.

**Comment by ghost** [comment]
Файлы перегенерировал.

Хм. Интересно на кодировку жалуется. Сейчас буду тестировать на Ubuntu

**Comment by ulysses4ever** [comment]
Там питон 2.7. Может, старый...

**Comment by ghost** [comment]
Возможно, у меня 3.4.

**Comment by ulysses4ever** [comment]
А, ну ясно, 2 и 3 вообще не совместимы. Третий у меня, вроде, есть.

**Comment by ghost** [comment]
Сейчас должно работать. Я строго прописал, какую версию python использовать.

**Comment by ghost** [comment]
Просто на Ubuntu по-умолчанию используется 2.7, а на Arch - 3.4.

**Comment by ulysses4ever** [comment]
Да, теперь ОК, если он установлен. Но о требуемой версии (3+) стоило бы
где-то написать, например, на Вики добавить.

**Comment by ghost** [comment]
Ну, можно и добавить. 
Я просто так понимаю когда устанавливается Python устанавливаются обе версии, а вот от дистрибутива уже зависит какая из них будет использоваться по умолчанию. Я сейчас смотрел даже на LiveCD Ubuntu установлены обе версии. И у меня есть обе версии, хотя я ставил только пакет `python` - версию намеренно не выбирал.
