### ISSUE TITLE
Весь конспект одним файлом

### ISSUE THREAD

**Issue by ulysses4ever** [mmcs-sfedu/PL_Lections_2014-2015#35]
Раз уже и так много всего генерируется, нельзя ли сделать генерацию одного длинного md-файла со всеми лекциями. И чтобы Pages потом его превращали в HTML. И ссылку где-то (на главной?) поставить.

И ещё: нельзя ли вторничную лекцию хоть в каком-то виде запушить (хоть в виде бранча, неотредактированную). Желательно, чтобы сырой вариант появлялся сразу.

**Comment by ghost** [comment]
В общем теперь `./build.py` публикует изменения в `./lecture/stream`. Т.е в этом файле будет находиться самая свежая информация. 
Когда очередная лекция готова к публикации, необходимо выполнить `./build.py -p`, после этого лекция появится в индексе.
Правда все это будет работать только в ветке `gh-pages` - придется расставлять теги.

**Comment by ghost** [comment]
Да, а зачем нужны все лекции одним файлом?

**Comment by ulysses4ever** [comment]
Чтобы делать ctrl+f полнотекстовый.

**Comment by ulysses4ever** [comment]
Честно говоря, название Stream вообще ни о чём не говорит. Может написать
«Все лекции» или что-то в этом духе.
