### ISSUE TITLE
Навигационная панель не прокручивается

### ISSUE THREAD

**Issue by xamgore** [mmcs-sfedu/PL_Lections_2014-2015#37]
Поломалась навигация на [тока](https://razykov.github.io/PL_Lections_2014-2015/lecture/02.html#structure) справа. Имеет фиксированное положение на странице, а не относительно экрана. :disappointed:

**Comment by ghost** [comment]
Дай же ты сначала закончить, потом баги вешай!!!

**Comment by ulysses4ever** [comment]
В жизни баги в любой момент вешаются, так что давайте не будем возмущаться!
