### ISSUE TITLE
Лекция 14

### ISSUE THREAD

**Issue by ghost** [mmcs-sfedu/PL_Lections_2014-2015#38]
@Admin в лекциях использовал термин moving-конструктор, однако в других источниках вместо moving используется move (Move semantics,  move-конструктор). 
Не стоит ли нам использовать ту же терминологию?

**Comment by ulysses4ever** [comment]
Да, я обратил на это внимание. Я думаю, что вообще лучше move, так как более широко употребляется, но считаю, что нужно писать так, как было в лекциях.

**Comment by ghost** [comment]
В конце лекции содержится описание оператора приведения типа:

``` cpp
operator double()
{
    return m/(double)n;
}
```

Мне кажется было бы правильнее так:

``` cpp
operator double() const
{
    return m/(double)n;
}
```

**Comment by ulysses4ever** [comment]
То же самое: видимо, вы правы, но я бы придерживался лекций. Вы можете повлиять на содержание лекций только явно: задав соответствующие вопросу на форуме или на лекции. Если он явно согласится, то исправлять.

**Comment by ghost** [comment]
Окей, понял.
