### ISSUE TITLE
Лекция 19

### ISSUE THREAD

**Issue by ghost** [mmcs-sfedu/PL_Lections_2014-2015#43]
Проблема!!!
Похоже, что вторую - самую интересную, часть 19 лекции я посеял. @xamgore можно тебя попросить восстановить недостающий материал.
Вообще странно это как-то, вроде постояно жму ctrl+s

**Comment by xamgore** [comment]
ЛООООЛ

Это знаешь как... Ты такой крутой пользуешь системы контроля версией, а потом внезапно оказывается, что забыл сделать коммит. И отвык от Ctrl+S. И всё, беда.

**Comment by xamgore** [comment]
К какому времени это надо сделать?

**Comment by ulysses4ever** [comment]
Вячеслав, не растраивайтесь, у всех бывает. Я в этом семестре два конспекта
писал на лекциях в MD, так точно также попадал пару раз.

Игорь, помогите, пожалуйста с восстановлением.

**Comment by ghost** [comment]
:laughing:  :laughing:  :laughing:

Все гораздо комичнее.
Просто не надо держать открытым окно с предыдущей лекцией - вторая половина была в исходниках семнадцатой. 
И главное помню точно, что все сохранял, а сегодня половины лекции не досчитался. :laughing:

**Comment by ulysses4ever** [comment]
Такое у меня как раз тоже было.
