### ISSUE TITLE
Лекция 26 декабря

### ISSUE THREAD

**Issue by ulysses4ever** [mmcs-sfedu/PL_Lections_2014-2015#47]
Будет? ;)

**Comment by xamgore** [comment]
:smile_cat:

**Comment by ghost** [comment]
Черновик залил, отредактирую чуть позже - у меня небольшая авария с диском.

**Comment by ulysses4ever** [comment]
@razykov спасибо!

**Comment by xamgore** [comment]
А есть последняя лекция? А, видел черновик.

**Comment by ghost** [comment]
Ну, честно говоря я ее так и не отредактировал. 
По-видимому она проходила в настолько непринужденной обстановке, что даже я теперь не знаю как из черновика сделать конспект лекции.

**Comment by xamgore** [comment]
Да и не надо. Если кому-то захочется (следующему курсу), то просто отдадим репо, или что-то в этом роде. Или создать какой-нибудь аккаунт для mmcs (типа организации), и пусть он там крутится. А Артём Михайлович или ещё кто добавляет туда контрибьютеров.
