### ISSUE TITLE
Что делать с репозиторием

### ISSUE THREAD

**Issue by xamgore** [mmcs-sfedu/PL_Lections_2014-2015#48]
@ulysses4ever, может, имеет смысл создать что-то вроде [такого же](https://github.com/php) коммьюнити, но только для sfedu mmcs. И переложить туда репозиторий. А вы (или кто-то ещё) будете уже давать доступ на контрибьютинг, если появятся желающие.

Думаю, @razykov уже не сильно нуждается в нём.

**Comment by ulysses4ever** [comment]
Не понял, что значит «для sfedu mmcs», но я бы ничего сейчас не делал.
Возникнет необходимость — просто форкнут.

**Comment by ulysses4ever** [comment]
Ой, я ссылку пропустил. Теперь понял. Да лень мне этим заниматься, не вижу смысла. Не очень понимаю профит от этих коммьюнити кроме пиара. А для пиара Мехмата я и так делаю не мало. Ещё и это как-то сил нет. И выгода не очевидна.

**Comment by xamgore** [comment]
О, классно выглядит!

**Comment by ulysses4ever** [comment]
А как туда добавляться вообще, в это MMCS SFEDU? Даже не вижу кнопки запроса на добавление (приходится вот тут писать).

**Comment by ghost** [comment]
По-видимому в этот "клуб" только по приглашению добавиться можно.
Вообще только сегодня заметил, что после переноса репозитория участники отуда удалились и теперь по-видимому доступ к репам регулируется через группы

**Comment by ulysses4ever** [comment]
Да, любопытно. Ну, так или иначе, спасибо!
