### ISSUE TITLE
Оформление README

### ISSUE THREAD

**Issue by ulysses4ever** [mmcs-sfedu/PL_Lections_2014-2015#7]
Сейчас получилось так, что ссылки внутри ридми правильные только, если заходить через github.io. А если смотреть репозитрий, то неправильные. Предлагаю 1) вынести индекс в файл index.md (просто переименовать текущий README), 2) создать маленький README.md с ссылкой на github.io.

**Comment by ghost** [comment]
Я так понимаю надо еще
`{% include_relative README.md %}` заменить на 
`{% include_relative index.md %}` ?

**Comment by ulysses4ever** [comment]
А index.html с этой магией вообще не нужен, если будет index.md просто со списком ссылок.

**Comment by ghost** [comment]
Ну, не знаю. Что-то он говорит `404 not found`. Пока что оставил `index.html`  с `{% include_relative index.md %}`. Может в `index.md` надо еще что-то прописать?

**Comment by ghost** [comment]
Сейчас, по-крайней мере, работает как надо.

**Comment by ulysses4ever** [comment]
Возможно, вы не дождались, пока он перебилдит (это может занять время). Я потом сам могу попробовать.

**Comment by ulysses4ever** [comment]
Вы были правы, я совсем забыл: фронт мэттр нужен (сверху). Я добавил и удалил index.html, теперь, вроде, работает.
