### ISSUE TITLE
Форматирование кода

### ISSUE THREAD

**Issue by xamgore** [mmcs-sfedu/PL_Lections_2014-2015#9]
Давайте придём к единому соглашению или хотя бы обсудим, чего хочется. 

``` cpp
if (hours < 24 && minutes < 60 && seconds < 60) {
    return true;  // just example
} else {
    return false;
}
```

K&R 1TBS очень хорош. Скобочки на той же строке ⇒ меньше блок кода ⇒ легче читать конспект. И пробелы между `if (..)` но не в объявлении функций: `void func(int a) { ...`

**Comment by ulysses4ever** [comment]
Я бы предпочёл, чтобы было максимально похоже на то, как пишут на лекции. Это поможет нам со студентами лучше понять друг друга на практике. Но вышесказанное кажется абсолютно разумным. За исключением того, конечно, что return true / else / return false никогда писать не надо.

**Comment by ghost** [comment]
Я, конечно, постараюсь в следующий раз сберечь форматирование Admin'а, но думаю он сам мало задумывается о форматировании кода, когда пишет на доске.

**Comment by ulysses4ever** [comment]
Это не важно, задумывается или нет, важно, что на практике при обсуждении таких вопросов надо хоть на что-то опираться, кроме общих соображений.

**Comment by ghost** [comment]
Xamgore, мы же вроде бы пришли к тому, что сохраняем форматирование кода как на лекциях. Зачем сейчас все переделывать под K&R?

**Comment by xamgore** [comment]
Патамушто.

Как по-вашему:

``` cpp
void print_odd(node<int>* p)
{
    while (p) 
    {
        if (p -> data % 2 == 0)
        {
            cout << p -> data << ' ';
        }
        p = p -> next;
    }
}
```

Как по-нашему:

``` cpp
void print_odd(node<int>* p) {
    while (p) {
        if (p -> data % 2 == 0) {
            cout << p -> data << ' ';
        }
        p = p -> next;
    }
}
```

Ладно, нужно — поменяю всё. Но это действительно как-то странно: "Вышесказанное разумно, но делать будем всё равно по-другому."

**Comment by ghost** [comment]
Xamgore, мне самому привычнее писать в K&R, но не надо забывать, что мы пишем конспект лекций, а не свой учебник по C++ - плохих учебников по этому языку и без нас навалом. Наша задача, все-таки, создать мостик между лекциями и практикой.
Вообще я разговаривал с Admin'ом по этому вопросу. Он сказал такую вещь, что на сегодняшний день работа движется в том направлении, что данный конспект будет годен для нас и наших одногруппников, но на следующий год его уже не перенесешь, поскольку структура нашего конспекта не совпадает с планом лекций.
Т.е. надо сейчас решить для чего мы все это делаем. Мы пишем для себя, сдаем экзамен, и гори все оно синем пламенем, или мы делаем электронный конспект согласованный с лекциями и пригодный для следующих поколений.

**Comment by ghost** [comment]
Просто я за это взялся с расчетом на то, чтобы сделать хотя бы черновой вариант конспекта лекций, который с небольшими переработками можно будет использовать в последующие годы. Это вот моя мотивация.

**Comment by xamgore** [comment]
> ..поскольку структура нашего конспекта не совпадает с планом лекций.

То есть не совпадает?

**Comment by ghost** [comment]
Во время лекций не всегда удается прочесть все так, как запланировано: что то приходится переносить на следующую лекцию из-за нехватки времени, что-то наоборот приходится рассказывать забегая вперед, потому, что это необходимо для практики. В результате появляются отклонения от плана.
Второй момент. Admin говорил о такой вещи как "излишняя детализация". Приводил в пример содержимое заголовочных файлов - У нас там полная таблица из Страуструпа а на лекции была рассказана только часть этой таблицы - "С таким же успехом можно взять готовую документацию."
Опят же, слова Admina, что для решения таких вот вопросов надо как-то скооперироваться, чтобы он писал нам план лекций, а мы его заполняли. Он даже сказал, что готов писать план в Markdown. Однако существует, на мой взгляд, гораздо большая проблема, Admin не хочет использовать для этих задач GitHub, мотивируя тем, что он для этого не предназначен. В общем-то он прав, но учитывая то, что GitHub, будучи не предназначенным для работы с конспектами, справляется с этой задачей получше сервисов предназначенных для этого, думаю, никто из нас не захочет переходить на что-то другое.

**Comment by xamgore** [comment]
Ну, просто "для себя" нет смысла. У меня вон есть пара красивых девушек с красивым почерком, у которых можно брать такие же "для себя" конспекты и смотреть всё, что нужно. Соглашусь, будем делать для следующих поколений, как бы пафосно ни звучало %)

Проблемы:

> излишняя детализация (пример заголовочных файлов)

Если возникает такая проблема, то пусть тот же Admin указывает на них; будем упрощать конспект, и формировать ссылки как для "дальнейшего чтения". issues никто не отменял.

> Прочитанный материал лекций текущего и следующего годов могут различаться.

Тогда нужно опираться не на модель "лекция — набор тем", а на тематические разделы. Как в конспектах wiki первого курса (списки, рекурсия, итд). Раз Admin предложил, то пусть оформляет такие разделы. Останется лишь разнести имеющийся материал, что нетрудно, мне кажется.

**Comment by xamgore** [comment]
Цитирую [Admin'a](http://it.mmcs.sfedu.ru/forum?func=view&amp;id=75511&amp;catid=164#75543):

> Вообще, это плохо, что наша вики такая разболтанная. Получается, что никто кроме меня в ней и не работает. И если она навернется, что вероятно, То все мои набранные тексты пострадают.
> 
> Я считаю GitHub не лучшим местом для набора лекций. Интерфейс там для этого убогий - GitHub явно для этого не предназначен. В некотором смысле тогда лучше использовать Google Docs.
> 
> По хорошему надо у нас поднимать приличную новую Wiki - пусть на маркдауне - пожалуйста - и тогда, скажем, в конспекте лекций я бы смог поучаствовать (сейчас это у меня есть в другом формате), а студенты бы подредактировали. 
> 
> Убедить переходить для набора лекций на GitHub, думаю, меня будет трудно.

Если Admin'у жалко свои труды в wiki, то надо просто перенести их в тот же markdown и сохранить где-нибудь здесь. Наверняка они окажутся очень полезными! и ничего не пропадёт.

Ещё он говорит, что главная страница репозитория (со списком файлов) плохо подходит для конспектов. Но на самом деле это то же самое, что зайти в [категории](http://it.mmcs.sfedu.ru/wiki/%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D1%8F:%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F) и сказать, что wiki — тоже очень убого. (Именно поэтому и там, и здесь есть титульные страницы.)

Admin считает, что GitHub не предназначен для ведения конспектов. По мне так git как раз и был предназначен для ведения текстовых документов (будь то исходные коды, или диссертация, или книга), а GitHub с его изумительно удобным интерфейсом — является отличным дополнением для процесса разработки, написания конспектов. Сейчас поясню.
- Вместо обсуждений в wiki здесь есть _issues_, где мы обсуждаем идеи, проблемы, их решения.
  А также _labels_ (или теги вроде bug, wantfix), для расстановки приоритетов.
- Всегда есть возможность попробовать что-то новое: branch, fork. Любой студент может предложить **новые** правки и их удобно здесь прослеживать! (история изменений)
- Здесь _удобный_ лог коммитов, видно, кому надо надавать по шапке, если что-то пошло не так.
- Мы можем подготовить автоматизированный скрипт для работы с репозиторием (например, для индексации)
- WYSIWYG по большей части отвратительны, здесь же ясная структура md и write\preview.
- Здесь также есть _pages_, которые сделал ulysless, для красивого оформления.
- Вести конспекты (любые другие проекты) на GitHub — это круто. Мои знакомые с других университетов просто завидуют, что мы здесь таким занимаемся.

> Админ, вы, как обычно, отстали от жизни, к которой, как мы все помним, и не приставали.

**Comment by ghost** [comment]
Надо теперь чтобы Admin поменял свое мнение о GitHub под впечатлением от прочитанного.
